spring:
 profiles:
  active:
  - dev
---
spring:
 profiles: dev #开发环境
 application:
  name: microservicecloud-config-eureka-client
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名
  client:
    registerWithEureka: false #false表示不向注册中心注册自己
    fetchRegistry: false #false表示自己端就是注册中心，职责是维护服务实例，不需要去检索服务
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
---
spring:
 profiles: test #开测试环境
 application:
  name: microservicecloud-config-eureka-client
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名
  client:
    registerWithEureka: false #false表示不向注册中心注册自己
    fetchRegistry: false #false表示自己端就是注册中心，职责是维护服务实例，不需要去检索服务
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
 #请保存为UTF-8格式